---
# tasks file for adv-prog-pkgs
- name: Install advanced language packages
  apt: name={{ adv_prog_pkgs_adv_lang }} state=latest

- name: Install source control packages
  apt: name={{ adv_prog_pkgs_souce_control }} state=latest

- name: Install code editor packages
  apt: name={{ adv_prog_pkgs_code_editor }} state=latest
