---
# handlers file for common
- name: Update desktop menu
  command:
    /usr/bin/update-desktop-database
- name: Suggest restart
  command: >-
    notify-send -u critical "JMU Software Change" 
    "Changes have been made to your machine that 
    will only take effect when you log out or 
    when you reboot. Please do this immediately."
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ item.uid }}"
  become: yes
  become_user: "{{ item.user }}"
  loop: "{{ real_users }}"
- name: Restart update manager
  shell:
    nohup mintupdate-launcher
  become: yes
  become_user: "{{ item.user }}"
  loop: "{{ real_users }}"
